CREATE TABLE Category
(
id int GENERATED BY DEFAULT AS IDENTITY (START WITH 3000, INCREMENT BY 1) NOT NULL,
parent_id int null,
name varchar(100) not null,
   constraint PK_CATEGORY primary key (id)
);

create table Manufacturer
(
   id int GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1) NOT NULL,
   name             varchar(100)                   not null,
   country		varchar(50) 			null,
   constraint PK_MANUFACTURER primary key (id)
);

create table Purchase
(
purchase_id int not null, 
purchase_prodID int not null, 
fio varchar(100) not null,
mail varchar(50) not null,
phone varchar(30) not null,
address varchar(100) not null,
   constraint PK_ORDER primary key (purchase_id)
);

create table Product
(
prod_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 2500, INCREMENT BY 1) NOT NULL,
   prod_cat_id               int                            not null,
   prod_man_id               int                            not null,
   prod_name            varchar(200)                   not null,
   prod_price           float                   not null,
   prod_desc            varchar(300)                   null,
   prod_avail           bit                           not null,
   prod_image           varchar(50)                   null,
   constraint PK_PRODUCTS primary key (prod_id)
);

create table Admins 
(
   login                varchar(15)                   not null,
   password             varchar(15)                   not null,
   enabled              bit     not null,
   constraint PK_ADMINS primary key (login)
);

create table Admins_roles 
(
   login                varchar(20)                   not null,
   roles                varchar(20)                      not null,
   constraint PK_ADMINS_ROLES primary key (login, roles)
);

create table Orders 
(
	order_id                        int                              not null,
	order_prodID                    int                              not null,
	fio                             varchar(100)                     not null,
	mail                            varchar(50)                      not null,
	phone                           varchar(30)                      not null,
	address                         varchar(100)                     not null   
);